### Install Numpy

In [1]:
! pip3 install numpy

### Import numpy 

In [2]:
import numpy as np

### Array

In [4]:
x = np.array ([1, 2, 3, 4, 5])
print (x)
print (type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([[1,2,3,4],[3,5,7,7]])
print (x)

In [ ]:
x0 = np.zeros((4,3))
print (x0)

In [ ]:
x1 = np.ones((3,4,6,5),dtype='int64') # Dimentions
print (x1)

In [ ]:
full = np.full((4,3),15)
print (full)

In [17]:
arrange = np.arange(10,0,-2)
print (arrange)

[10  8  6  4  2]


In [29]:
print(np.arange(0,15,2).reshape(4,2))

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


In [ ]:
print (np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [6]:
print(np.eye(5, k = 0, dtype="int64"))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [20]:
x = np.ones((10000,10000), dtype="int64")
print("thanks")
#print (id(x))
#y = x
#y[0] = 1
#print (id(y))
#print (len(x))
print (x.size)

thanks
100000000


## Practice Set


#### Question 1 : Create a 1D Array containg numbers from 1 to 10

In [4]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


#### Question 2 : Create a 3 x 3 matrix of all zeros, and another of all ones

In [8]:
print(np.zeros((3,3), dtype="int64"))
print(np.ones((3,3), dtype="int64"))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Indexing & Slicing

In [11]:
arr = np.arange(10)
print (arr[-3 : - 12 : -2])

[7 5 3 1]


In [30]:
x = 4
y = 5
arr = np.arange(1,21).reshape(x,y)
print (arr)
print()
print (arr[::x-1, ::y - 1])
print()
print (*arr[1:3, -2:: - 1])
print()
print (*arr[-1:-4:-2, -2:0: - 2])
print()
print (*arr[1, 1::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  5]
 [16 20]]

[9 8 7 6] [14 13 12 11]

[19 17] [9 7]

7 8 9 10


### DATA Manipulation

In [14]:
x = np.array([1 ,2.5 ,"Hello"])
x = np.array([1 ,2.5 ,4.3])
x = x.astype('int64')
print (*x)


1 2 4


### Arithmatic Operation

In [27]:
arr = np.array([1,2,3,4,5,6,7])
arr1 = np.array([2,3,4,5,6,7,10])
print (arr//2)
print (arr**2)
print (arr + arr1)
print (arr * arr1)

[0 1 1 2 2 3 3]
[ 1  4  9 16 25 36 49]
[ 3  5  7  9 11 13 17]
[ 2  6 12 20 30 42 70]


In [28]:
x = np.arange(6).reshape(2,3)
y = np.arange(3)
print (x + y)

[[0 2 4]
 [3 5 7]]


### Comparison Operator

In [31]:
x = np.arange (10)
y = np.arange (1,11)
print (*x)
print (*y)
print (*(x==y))
print (*(x<y))

0 1 2 3 4 5 6 7 8 9
1 2 3 4 5 6 7 8 9 10
False False False False False False False False False False
True True True True True True True True True True


## np.random 
- Seed 
- Rand

In [ ]:
np.random.seed(2)
print (np.random.rand(10))
print (np.random.randn(100))


In [45]:
import matplotlib.pyplot as plt

In [ ]:
fig, ax = plt.subplots()   
np.random.seed(50)
x = np.sort(np.random.randn(500) )
ax.plot(range(500), x**2, marker='.')
plt.show()                        


In [ ]:
np.random.seed(50)
x = np.random.randn(5000)  # don't sort

fig, ax = plt.subplots()   
ax.hist(x, bins=30, density=True)
plt.show()

In [77]:
lst = np.arange (23)
y = np.random.choice(lst,25)
print (*y)

20 8 19 0 5 1 16 4 8 14 1 9 1 5 10 19 15 3 2 11 12 12 19 18 12


In [86]:
lst = np.array([5,2,62,74,2,243,67])
np.random.shuffle(lst)
print (lst)


[243  62   2   2   5  67  74]


## Class Questions

In [94]:
np.random.seed(42)
x = [np.random.randint(1,7) for i in range (10)]
print (x)

[4, 5, 3, 5, 5, 2, 3, 3, 3, 5]


In [95]:
lst = ['Aman' , 'Priya', 'Rahul' , 'Sneha' , 'Vikram']
np.random.choice(lst,3)


array(['Sneha', 'Rahul', 'Vikram'], dtype='<U6')

### Basic Statistics

In [98]:
arr = np.arange(6).reshape(2,3)
print (arr)
print (arr.min())
print (arr.min(axis=0), "column min")
print (arr.min(axis=1), "row min")

[[0 1 2]
 [3 4 5]]
0
[0 1 2] column min
[0 3] row min


In [ ]:
arr = np.arange(6,12).reshape(2,3)
print (arr)
print (arr.sum())
print (arr.sum(axis=0), "column sum")
print (arr.sum(axis=1), "row sum")

In [107]:
print (*(*np.median(arr, axis=0).astype('int64'), *np.median(arr, axis=1).astype('int64')))

7 8 9 7 10


### np.where()



In [7]:
marks = np.array([92,76,45,90,10])
idx = np.where(marks > 10)[0]
print ("raw return" , *idx)

raw return 0 1 2 3
